#!/bin/sh

MYROOT=`/usr/bin/dirname $0`
MYNAME=`/bin/basename $0`

cd $MYROOT || exit 1
MYDIR=`/bin/pwd`

if [ $# -eq 1 ]; then
  INIT_TIME=$1
else 
  echo "Usage: $0 YYYYMMDDhh"
  exit 1
fi

INIT_TIME=$1
if [ ${#INIT_TIME} -ne 10 ]; then
  echo "Invalid initial time ${INIT_TIME}"
  echo "Usage: $0 YYYYMMDDhh"
  exit 1
fi

D=`/bin/date -d "${INIT_TIME:0:8} ${INIT_TIME:8:2}:00:00" +%Y%m%d%H 2>/dev/null`
if [ "$INIT_TIME" != "$D" ]; then
  echo "Invalid initial time ${INIT_TIME}"
  echo "Usage: $0 YYYYMMDDhh"
  exit 1
fi

BEG_TIME=`/bin/date -d "${INIT_TIME:0:8} ${INIT_TIME:8:2}:00:00 $CTM_SKIP_N_DAYS days" +%Y%m%d%H`
let "ndays = $CTM_SIM_N_DAYS - 1"
END_TIME=`/bin/date -d "${BEG_TIME:0:8} ${BEG_TIME:8:2}:00:00 $ndays days" +%Y%m%d%H`

DataPath=outputs/run.OP_mm5_cb05cl
Prefix=CCTM_V5g_ebi_cb05cl_ae5_aq_mpich2

/usr/bin/find $DataPath -type l -exec /bin/rm -v {} \;

for DOMAINS_RES in $G_DOMAINS_RES_gov
do
  for datatype in ACONC AEROVIS CGRID CONC DRYDEP WETDEP1
  do
    Size=
    CUR_TIME=$BEG_TIME
    while [ "$CUR_TIME" -le "$END_TIME" ]
    do
      CUR_JDATE=`/bin/date -d "${CUR_TIME:0:8}" +%Y%j`
      OutFile="${DataPath}/${DOMAINS_RES}km/${Prefix}.${datatype}.${CUR_JDATE}"
      if [ -s $OutFile ]; then
        fsize=`/usr/bin/stat -c "%s" $OutFile`
        if [ -z ${Size} ]; then
          Size=$fsize
        fi
        if [ $fsize != ${Size} ]; then
          echo "Invalid CMAQ output file $OutFile, size = $fsize"
          exit 1
        fi
      else
        echo $OutFile not exist
        exit 1
      fi
      CUR_TIME=`/bin/date -d "${CUR_TIME:0:8} ${CUR_TIME:8:2}:00:00 1 day" +%Y%m%d%H`
    done
  done
done  

exit 0
