#!/bin/sh
#

if [ $# -ne 2 ]; then
  echo "Usage: $0 InitTime OutputDir"
  exit 1
fi

InitTime=$1
OutputDir=$2

if [ -d $OutputDir ]; then
  echo "Output directory $OutputDir already exists"
  if [ $CTM_CLEAN_OUTPUT -eq 1 ]; then
    echo "Remove Output directory"
    /bin/rm -r -f $OutputDir
  else
    echo "Keep Output directory"
  fi
fi

if [ ! -d $OutputDir ]; then
  /bin/mkdir -p $OutputDir || {
    echo "Failed to create output directory $OutputDir"
    exit 1
  }
fi

for DOMAINS_RES in ${G_DOMAINS_RES_AQMS_gov}
do
  [ -f outputs/$DOMAINS_RES/GRIDDESC ] || {
    echo "outputs/$DOMAINS_RES/GRIDDESC does not exist"
    exit 1
  }
done

for DOMAINS_RES in ${G_DOMAINS_RES_AQMS_gov}
do
  if [ ! -d $OutputDir/${DOMAINS_RES}km ]; then
    /bin/mkdir $OutputDir/${DOMAINS_RES}km || {
      echo "Failed to create output subdirectory $OutputDir/${DOMAINS_RES}km"
      exit 1
    }
  fi
  /usr/bin/rsync -av outputs/$DOMAINS_RES/ $OutputDir/${DOMAINS_RES}km/ || {
    echo "Failed to run /usr/bin/rsync -av outputs/$DOMAINS_RES/ $OutputDir/${DOMAINS_RES}km/"
    exit 1
  }
done

echo "MCIP Output data saved to $OutputDir"

exit 0
