#!/bin/sh

MYROOT=`/usr/bin/dirname $0`
MYNAME=`/bin/basename $0`

cd $MYROOT || exit 1
MYDIR=`/bin/pwd`

if [ $# -eq 1 ]; then
  INIT_TIME=$1
else 
  echo "Usage: $0 YYYYMMDDhh"
  exit 1
fi

INIT_TIME=$1
if [ ${#INIT_TIME} -ne 10 ]; then
  echo "Invalid initial time ${INIT_TIME}"
  echo "Usage: $0 YYYYMMDDhh"
  exit 1
fi

D=`/bin/date -d "${INIT_TIME:0:8} ${INIT_TIME:8:2}:00:00" +%Y%m%d%H 2>/dev/null`
if [ "$INIT_TIME" != "$D" ]; then
  echo "Invalid initial time ${INIT_TIME}"
  echo "Usage: $0 YYYYMMDDhh"
  exit 1
fi

END_TIME=`/bin/date -d "${INIT_TIME:0:8} ${INIT_TIME:8:2}:00:00 ${MET_SIM_N_DAYS} days" +%Y%m%d%H`

DataPath=outputs/${INIT_TIME:0:4}/${INIT_TIME:0:6}/${INIT_TIME}
Prefix=wrfout

DOMAINS_GRID=`ls $DataPath | grep "wrfout" | cut -c 8-10 | uniq`
for WRF_GRID in $DOMAINS_GRID
do
  dt=$INIT_TIME
  Size=
  while [ "$dt" -le "$END_TIME" ]
  do
    OutFile="${DataPath}/${Prefix}_${WRF_GRID}_${dt:0:4}-${dt:4:2}-${dt:6:2}_${dt:8:2}:00:00"
    if [ -s $OutFile ]; then
      fsize=`/usr/bin/stat -c "%s" $OutFile`
      if [ -z ${Size} ]; then
        Size=$fsize
      fi
      if [ $fsize != ${Size} ]; then
        echo "Invalid WRF output file $OutFile, size = $fsize"
        exit 1
      fi
    else
      echo $OutFile not exist
      exit 1
    fi
    dt=`/bin/date -d "${dt:0:8} ${dt:8:2}:00:00 1 hour" +%Y%m%d%H`
  done
done  

exit 0
