#!/bin/sh
#
# Search CMAQ output data for day0 and link the data files to input directory
#
if [ $# -eq 1 ]; then
  INIT_TIME=$1
else
  echo "Usage: $0 YYYYMMDDhh"
  exit 1
fi

PATH_SYSDIR=${PATH_SYSDIR-/home/pathsys}
DATA_CMAQ_OUTPUT=${DATA_CMAQ_OUTPUT-/home/pathop/fcst_data/cmaq}

$PATH_SYSDIR/bin/check_yyyymmddhh $INIT_TIME || exit 1

Output1_init_time=`/bin/date -d "${INIT_TIME:0:8} ${INIT_TIME:8:2}:00:00 1 day  ago" +%Y%m%d%H`
Output2_init_time=`/bin/date -d "${INIT_TIME:0:8} ${INIT_TIME:8:2}:00:00 2 days ago" +%Y%m%d%H`
Output3_init_time=`/bin/date -d "${INIT_TIME:0:8} ${INIT_TIME:8:2}:00:00 3 days ago" +%Y%m%d%H`

Prefix=CCTM_V5g_ebi_cb05cl_ae5_aq_mpich2

JDay0=`${PATH_SYSDIR}/bin/ymd2yj ${INIT_TIME:0:8}`
if [ $FC_MODE -eq 1 ]; then
  JDay0=`${PATH_SYSDIR}/bin/yj_prev $JDay0`
fi

for Output_init_time in $Output1_init_time $Output2_init_time $Output3_init_time
do
  OutputDir=${DATA_CMAQ_OUTPUT}/${Output_init_time:0:4}/${Output_init_time:0:6}/${Output_init_time}
  if [ ! -e $OutputDir ]; then
    echo "Output directory ${OutputDir} does not exist"
    continue
  fi
  found=1
  for km in $G_DOMAINS_RES_CMAQ
  do
    files=`/usr/bin/find $OutputDir/${km}km -mindepth 1 -maxdepth 1 -type f -name "${Prefix}.*.${JDay0}" -print`
    if [ -z "$files" ]; then
      found=0
      break
    fi
  done
  if [ $found -eq 0 ]; then
    echo "No valid CCTM_V5g_ebi_cb05cl_ae5_aq_mpi_pg64_mpich2....${JDay0} found in $OutputDir"
    continue
  fi

  for km in $G_DOMAINS_RES_CMAQ
  do
    CMAQ_output_dir=outputs/run.OP_mm5_cb05cl/${km}km
    if [ ! -d $CMAQ_output_dir ]; then
      /bin/mkdir -p $CMAQ_output_dir || {
        echo "Failed to create $CMAQ_output_dir directory"
        exit 1
      }
    fi
    files=`/usr/bin/find $OutputDir/${km}km -mindepth 1 -maxdepth 1 -type f -name "${Prefix}.*.${JDay0}" -print`
    for a in $files
    do
      echo /bin/ln -sf $a $CMAQ_output_dir/
      /bin/ln -sf $a $CMAQ_output_dir/
    done 
  done
  exit 0
done
echo "No valid output found for day0 = $INIT_TIME"
exit 2
