#!/bin/sh

MYROOT=`/usr/bin/dirname $0`
MYNAME=`/bin/basename $0`

cd $MYROOT || exit 1
MYDIR=`/bin/pwd`

if [ $# -eq 2 ]; then
  BEG_GDATE=$1
  END_TOM_GDATE=$2
else 
  echo "Usage: $0 YYYYMMDD YYYYMMDD"
  exit 1
fi

BEG_GDATE=$1
if [ ${#BEG_GDATE} -ne 8 ]; then
  echo "Invalid initial date ${BEG_GDATE}"
  echo "Usage: $0 YYYYMMDD YYYYMMDD"
  exit 1
fi
D=`/bin/date -d "${BEG_GDATE}" +%Y%m%d 2>/dev/null`
if [ "$BEG_GDATE" != "$D" ]; then
  echo "Invalid initial date ${BEG_GDATE}"
  echo "Usage: $0 YYYYMMDD YYYYMMDD"
  exit 1
fi

END_TOM_GDATE=$2
if [ ${#END_TOM_GDATE} -ne 8 ]; then
  echo "Invalid ending date ${END_TOM_GDATE}"
  echo "Usage: $0 YYYYMMDD YYYYMMDD"
  exit 1
fi
D=`/bin/date -d "${END_TOM_GDATE}" +%Y%m%d 2>/dev/null`
if [ "$END_TOM_GDATE" != "$D" ]; then
  echo "Invalid ending date ${END_TOM_GDATE}"
  echo "Usage: $0 YYYYMMDD YYYYMMDD"
  exit 1
fi

FileTypes="cr kv_ob70 lu qa tp uv zp"

DataPath=Output
Prefix=camx

#for DOMAINS_RES in 1 3 9 27
for DOMAINS_RES in $G_DOMAINS_RES_AQMS_gov
do
  for ft in $FileTypes
  do
    CUR_GDATE=${BEG_GDATE}
    Size=
    while [ "$CUR_GDATE" -lt "$END_TOM_GDATE" ]
    do
      OutFile="${DataPath}/${DOMAINS_RES}/camx_${ft}.${CUR_GDATE}.${DOMAINS_RES}km.bin"
      if [ -s $OutFile ]; then
        fsize=`/usr/bin/stat -c "%s" $OutFile`
        if [ -z ${Size} ]; then
          Size=$fsize
        fi
        if [ $fsize != ${Size} ]; then
          echo "Invalid Met2CAMx output file $OutFile, size = $fsize"
          exit 1
        fi
      else
        echo $OutFile not exist
        exit 1
      fi
      CUR_GDATE=`/bin/date -d "${CUR_GDATE} 1 day" +%Y%m%d`
    done
  done
done  

exit 0
