#!/bin/sh

MYROOT=`/usr/bin/dirname $0`
MYNAME=`/bin/basename $0`

cd $MYROOT || exit 1
MYDIR=`/bin/pwd`

if [ $# -eq 2 ]; then
  INIT_DATE=$1
  END_DATE=$1
else 
  echo "Usage: $0 YYYYMMDD YYYYMMDD"
  exit 1
fi

INIT_DATE=$1
if [ ${#INIT_DATE} -ne 8 ]; then
  echo "Invalid initial date ${INIT_DATE}"
  echo "Usage: $0 YYYYMMDD YYYYMMDD"
  exit 1
fi
D=`/bin/date -d "${INIT_DATE}" +%Y%m%d 2>/dev/null`
if [ "$INIT_DATE" != "$D" ]; then
  echo "Invalid initial date ${INIT_DATE}"
  echo "Usage: $0 YYYYMMDD YYYYMMDD"
  exit 1
fi

END_DATE=$2
if [ ${#END_DATE} -ne 8 ]; then
  echo "Invalid ending date ${END_DATE}"
  echo "Usage: $0 YYYYMMDD YYYYMMDD"
  exit 1
fi
D=`/bin/date -d "${END_DATE}" +%Y%m%d 2>/dev/null`
if [ "$END_DATE" != "$D" ]; then
  echo "Invalid ending date ${END_DATE}"
  echo "Usage: $0 YYYYMMDD YYYYMMDD"
  exit 1
fi

FileTypes="cr kv_ob70 lu qa tp uv zp"

DataPath=Output
Prefix=camx

#for dom in 1 3 9 27
for dom in $DOMAINS
do
  for ft in $FileTypes
  do
    da=${INIT_DATE}
    Size=
    while [ "$da" -lt "$END_DATE" ]
    do
      OutFile="${DataPath}/${dom}/camx_${ft}.${da}.${dom}km.bin"
      if [ -s $OutFile ]; then
        fsize=`/usr/bin/stat -c "%s" $OutFile`
        if [ -z ${Size} ]; then
          Size=$fsize
        fi
        if [ $fsize != ${Size} ]; then
          echo "Invalid Met2CAMx output file $OutFile, size = $fsize"
          exit 1
        fi
      else
        echo $OutFile not exist
        exit 1
      fi
      da=`/bin/date -d "${da} 1 day" +%Y%m%d`
    done
  done
done  

exit 0
